[package]
name = "tapir-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
sdl2 = { version = "0.35", features = ["bundled", "static-link"] }
mgba = { path = "../mgba" }
crossbeam = "0.8"
